### ISSUE TITLE
First version goals

### ISSUE THREAD

**Issue by phildotdev** [fephil/lesnar#1]
- [x] - Virtualbox support,
- [x] - Parallels support,
- [x] - Vagrant hosts updater,
- [x] - Vagrant guest additions updater,
- [x] - Ansible: PHP,
- [x] - Ansible: MariaDB,
- [x] - Ansible: nginx,
- [x] - Ansible: Basic global vars,
- [x] - nginx logging,
- [x] - readme.
